/* The following code was generated by JFlex 1.3.5 on 10/24/19, 3:36 PM */

/*
  This example comes from a short article series in the Linux 
  Gazette by Richard A. Sevenich and Christopher Lopes, titled
  "Compiler Construction Tools". The article series starts at

  http://www.linuxgazette.com/issue39/sevenich.html

  Small changes and updates to newest JFlex+Cup versions 
  by Gerwin Klein
*/

/*
  Commented By: Christopher Lopes
  File Name: lcalc.flex
  To Create: > jflex lcalc.flex

  and then after the parser is created
  > javac Lexer.java
*/
   
/* --------------------------Usercode Section------------------------ */
   
import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 10/24/19, 3:36 PM from the specification file
 * <tt>file:/home/luizsetten/Downloads/analisador_sintatico_completo_gerador_codigo/sintatico_completo/lcalc.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  2,  0,  3,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    10,  0,  0,  0,  0,  0,  0,  0, 18, 19,  9, 13,  0, 14,  6,  8, 
     4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  0, 12, 22, 23, 24,  0, 
     0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 20,  0, 21,  0,  7, 
     0, 29, 11, 27, 15, 25, 36, 33, 11, 16, 11, 11, 30, 34, 35, 32, 
    31, 39, 28, 26, 37, 38, 17, 11, 11, 11, 11,  0,  0,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    40,    80,    40,   120,   160,   200,   240,    40,    40, 
       40,    40,   280,   320,    40,    40,    40,    40,   360,    40, 
       40,   400,   440,   480,   520,   560,   600,   640,   680,   720, 
      120,   760,   800,   840,   880,   200,   920,    40,   960,  1000, 
     1040,  1080,  1120,  1160,  1200,  1240,   200,  1280,  1320,  1360, 
     1400,  1440,  1480,   200,  1520,  1560,  1600,  1640,  1680,  1720, 
     1760,   200,  1800,  1840,  1880,  1920,   200,  1960,  2000,  2040, 
     2080,  2120,  2160,  2200,  2240,  2280,  2320,  2360,   200,  2400, 
     2440,   200,  2480,  2520,  2560,   200,  2600,  2640,  2680,  2720, 
     2760,   200,  2800,   200,  2840,  2880,   200,  2920,   200,  2960, 
     3000,  3040,   200,  3080,  3120,  3160,  3200,  3240,  3280,  3320, 
     3360,  3400,   200,   200,  3440,   200,  3480,  3520,   200,  3560, 
     3600,  3640,   200,   200,  3680,  3720,  3760,  3800,  3840,   200, 
     3880,   200,  3920,  3960,   200,  4000,   200
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\2\4\1\5\1\6\1\2\1\7\1\10"+
    "\1\11\1\4\1\7\1\12\1\13\1\14\1\15\1\16"+
    "\1\7\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\7\1\30\1\31\1\32\1\33\1\34"+
    "\2\7\1\35\1\36\3\7\52\0\1\4\51\0\2\37"+
    "\1\40\45\0\2\6\1\40\45\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\17\7\10\0\1\41"+
    "\1\42\42\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\1\7\1\43\1\7\7\0\1\44\16\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\3\7\7\0\12\7"+
    "\1\45\4\7\16\0\1\46\35\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\1\7\1\47\10\7"+
    "\1\50\4\7\4\0\2\7\1\0\1\7\3\0\1\7"+
    "\3\0\3\7\7\0\1\51\16\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\1\52\16\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\3\7"+
    "\7\0\14\7\1\53\2\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\1\54\16\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\3\7\1\55\1\56\12\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\15\7\1\57\1\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\3\7"+
    "\7\0\4\7\1\60\12\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\1\7\1\61\1\7\7\0\4\7"+
    "\1\62\1\63\7\7\1\64\1\7\4\0\2\40\46\0"+
    "\2\41\4\0\2\41\3\0\3\41\7\0\17\41\10\42"+
    "\1\0\1\65\36\42\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\2\7\1\66\7\0\17\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\1\7\1\67\1\7"+
    "\7\0\14\7\1\70\2\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\2\7\1\71\14\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\3\7"+
    "\7\0\14\7\1\72\1\7\1\73\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\12\7\1\74"+
    "\4\7\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\3\7\7\0\14\7\1\75\2\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\1\76\16\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\1\7"+
    "\1\77\1\7\7\0\17\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\7\7\1\100\7\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\3\7"+
    "\7\0\1\7\1\101\1\7\1\102\13\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\3\7\7\0\7\7"+
    "\1\103\7\7\4\0\2\7\1\0\1\7\3\0\1\7"+
    "\3\0\3\7\7\0\11\7\1\104\5\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\3\7\7\0\2\7"+
    "\1\105\14\7\4\0\2\7\1\0\1\7\3\0\1\7"+
    "\3\0\3\7\7\0\15\7\1\106\1\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\3\7\7\0\12\7"+
    "\1\107\4\7\10\0\1\4\43\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\2\7\1\110\14\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\3\7"+
    "\7\0\1\111\16\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\3\7\1\112\13\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\4\7\1\113\12\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\15\7\1\114\1\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\4\7\1\115\12\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\7\7\1\116\7\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\4\7\1\117\12\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\10\7\1\120\6\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\1\7\1\121\15\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\4\7\1\122\12\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\1\123\1\124\4\7\1\125\10\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\4\7\1\126"+
    "\12\7\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\3\7\7\0\14\7\1\127\2\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\2\7\1\130"+
    "\14\7\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\1\7\1\131\1\7\7\0\17\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\1\7\1\132\1\7\7\0"+
    "\17\7\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\3\7\7\0\1\133\16\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\7\7\1\134\7\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\3\7"+
    "\7\0\4\7\1\135\12\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\7\7\1\136\7\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\3\7"+
    "\7\0\3\7\1\137\13\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\3\7\1\140\13\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\3\7"+
    "\7\0\7\7\1\141\7\7\4\0\2\7\1\0\1\7"+
    "\3\0\1\7\3\0\3\7\7\0\12\7\1\142\4\7"+
    "\4\0\2\7\1\0\1\7\3\0\1\7\3\0\3\7"+
    "\7\0\1\143\16\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\4\7\1\144\12\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\15\7\1\145\1\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\4\7\1\146\12\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\7\7\1\147\7\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\3\7\1\150\13\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\2\7\1\151"+
    "\7\0\17\7\4\0\2\7\1\0\1\7\3\0\1\7"+
    "\3\0\3\7\7\0\12\7\1\152\4\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\3\7\7\0\12\7"+
    "\1\153\4\7\4\0\2\7\1\0\1\7\3\0\1\7"+
    "\3\0\3\7\7\0\4\7\1\154\12\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\3\7\7\0\16\7"+
    "\1\155\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\3\7\7\0\3\7\1\156\13\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\4\7\1\157"+
    "\12\7\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\3\7\7\0\7\7\1\160\7\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\7\7\1\161"+
    "\7\7\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\3\7\7\0\4\7\1\162\12\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\14\7\1\163"+
    "\2\7\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\3\7\7\0\7\7\1\164\7\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\11\7\1\165"+
    "\5\7\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\3\7\7\0\15\7\1\166\1\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\3\7\7\0\4\7\1\167"+
    "\12\7\4\0\2\7\1\0\1\7\3\0\1\7\3\0"+
    "\3\7\7\0\12\7\1\170\4\7\4\0\2\7\1\0"+
    "\1\7\3\0\1\7\3\0\1\7\1\171\1\7\7\0"+
    "\13\7\1\172\3\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\7\7\1\173\7\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\4\7\1\174\12\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\4\7\1\175\12\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\14\7\1\176\2\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\12\7\1\177\4\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\1\7\1\200"+
    "\1\7\7\0\17\7\4\0\2\7\1\0\1\7\3\0"+
    "\1\7\3\0\3\7\7\0\12\7\1\201\4\7\4\0"+
    "\2\7\1\0\1\7\3\0\1\7\3\0\3\7\7\0"+
    "\1\202\16\7\4\0\2\7\1\0\1\7\3\0\1\7"+
    "\3\0\1\7\1\203\1\7\7\0\17\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\3\7\7\0\11\7"+
    "\1\204\5\7\4\0\2\7\1\0\1\7\3\0\1\7"+
    "\3\0\3\7\7\0\14\7\1\205\2\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\3\7\7\0\2\7"+
    "\1\206\14\7\4\0\2\7\1\0\1\7\3\0\1\7"+
    "\3\0\3\7\7\0\7\7\1\207\7\7\4\0\2\7"+
    "\1\0\1\7\3\0\1\7\3\0\1\7\1\210\1\7"+
    "\7\0\17\7\4\0\2\7\1\0\1\7\3\0\1\7"+
    "\3\0\3\7\7\0\7\7\1\211\7\7";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  1,  9,  1,  1,  1,  1,  9,  9,  9,  9,  1,  1,  9,  9, 
     9,  9,  1,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1, 
     1,  0,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    /* To create a new java_cup.runtime.Symbol with information about
       the current token, the token will have no value in this
       case. */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[4040];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 136: 
          {   return symbol(sym.STARTFUNC); }
        case 138: break;
        case 131: 
          {   return symbol(sym.ENDFUNC);   }
        case 139: break;
        case 129: 
          {   return symbol(sym.DECLFLOAT); }
        case 140: break;
        case 123: 
          {   return symbol(sym.PROGRAM);   }
        case 141: break;
        case 122: 
          {   return symbol(sym.ENQUANTO);  }
        case 142: break;
        case 118: 
          {   return symbol(sym.FIMPARA);   }
        case 143: break;
        case 115: 
          {   return symbol(sym.RETORNO);   }
        case 144: break;
        case 113: 
          {   return symbol(sym.WRITELINE); }
        case 145: break;
        case 112: 
          {   return symbol(sym.DECLINT);   }
        case 146: break;
        case 21: 
          {   return symbol(sym.E);         }
        case 147: break;
        case 20: 
          {   return symbol(sym.GREATER);   }
        case 148: break;
        case 19: 
          {   return symbol(sym.EQUALS);    }
        case 149: break;
        case 18: 
          {   return symbol(sym.LESS);      }
        case 150: break;
        case 17: 
          {   return symbol(sym.RBRCKT);    }
        case 151: break;
        case 16: 
          {   return symbol(sym.LBRCKT);    }
        case 152: break;
        case 15: 
          {   return symbol(sym.RPAREN);    }
        case 153: break;
        case 14: 
          {   return symbol(sym.LPAREN);    }
        case 154: break;
        case 8: 
          {   return symbol(sym.TIMES);     }
        case 155: break;
        case 9: 
          {   return symbol(sym.SEMI);      }
        case 156: break;
        case 10: 
          {   return symbol(sym.PLUS);      }
        case 157: break;
        case 11: 
          {   return symbol(sym.MINUS);     }
        case 158: break;
        case 35: 
          {   return symbol(sym.DE);        }
        case 159: break;
        case 37: 
          {   return symbol(sym.ATTRIB);    }
        case 160: break;
        case 40: 
          {   return symbol(sym.IFF);       }
        case 161: break;
        case 46: 
          {   return symbol(sym.OU);        }
        case 162: break;
        case 53: 
          {   return symbol(sym.DIVIDE);    }
        case 163: break;
        case 61: 
          {   return symbol(sym.ATE);       }
        case 164: break;
        case 67: 
          {   return symbol(sym.ENDPRG);    }
        case 165: break;
        case 78: 
          {   return symbol(sym.READLINE);  }
        case 166: break;
        case 81: 
          {   return symbol(sym.PARA);      }
        case 167: break;
        case 85: 
          {   return symbol(sym.FACA);      }
        case 168: break;
        case 91: 
          {   return symbol(sym.THENN);     }
        case 169: break;
        case 93: 
          {   return symbol(sym.ELSEE);     }
        case 170: break;
        case 96: 
          {   return symbol(sym.PASSO);     }
        case 171: break;
        case 98: 
          {   return symbol(sym.ENDELSE);   }
        case 172: break;
        case 102: 
          {   return symbol(sym.STARTPRG);  }
        case 173: break;
        case 111: 
          {   return symbol(sym.FUNCAO);    }
        case 174: break;
        case 31: 
          {  /* System.out.print(yytext()); */
                         return symbol(sym.FLOATT, yytext());  }
        case 175: break;
        case 2: 
        case 3: 
          {  /* just skip what was found, do nothing */  }
        case 176: break;
        case 4: 
        case 5: 
          {  /* System.out.print(yytext()); */
                         return symbol(sym.INTT,yytext());  }
        case 177: break;
        case 6: 
        case 12: 
        case 13: 
        case 22: 
        case 23: 
        case 24: 
        case 25: 
        case 26: 
        case 27: 
        case 28: 
        case 29: 
        case 34: 
        case 36: 
        case 38: 
        case 39: 
        case 41: 
        case 42: 
        case 43: 
        case 44: 
        case 45: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 51: 
        case 54: 
        case 55: 
        case 56: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 62: 
        case 63: 
        case 64: 
        case 65: 
        case 68: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 77: 
        case 79: 
        case 80: 
        case 82: 
        case 83: 
        case 84: 
        case 86: 
        case 87: 
        case 88: 
        case 89: 
        case 90: 
        case 92: 
        case 94: 
        case 95: 
        case 97: 
        case 99: 
        case 100: 
        case 101: 
        case 103: 
        case 104: 
        case 105: 
        case 106: 
        case 107: 
        case 108: 
        case 109: 
        case 110: 
        case 114: 
        case 116: 
        case 117: 
        case 119: 
        case 120: 
        case 121: 
        case 124: 
        case 125: 
        case 126: 
        case 127: 
        case 128: 
        case 130: 
        case 132: 
        case 133: 
        case 135: 
          {  /* System.out.print(yytext()); */
                         return symbol(sym.ID, yytext()); }
        case 178: break;
        case 32: 
          {  /* just skip what was found, do nothing */  }
        case 179: break;
        case 134: 
          {   return symbol(sym.FIMENQUANTO); }
        case 180: break;
        case 66: 
          {   return symbol(sym.NAO);        }
        case 181: break;
        case 1: 
        case 7: 
          {  throw new Error("Illegal character <"+yytext()+">");  }
        case 182: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
