
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.util.Stack;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141204 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\112\000\002\002\003\000\002\002\004\000\002\017" +
    "\004\000\002\017\002\000\002\027\002\000\002\030\002" +
    "\000\002\020\020\000\002\020\012\000\002\031\002\000" +
    "\002\015\005\000\002\015\002\000\002\032\002\000\002" +
    "\033\002\000\002\003\011\000\002\004\004\000\002\004" +
    "\002\000\002\005\003\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\034\002\000\002" +
    "\007\006\000\002\035\002\000\002\010\006\000\002\036" +
    "\002\000\002\037\002\000\002\040\002\000\002\012\014" +
    "\000\002\041\002\000\002\013\016\000\002\042\002\000" +
    "\002\014\010\000\002\016\004\000\002\016\004\000\002" +
    "\026\003\000\002\026\003\000\002\043\002\000\002\011" +
    "\010\000\002\044\002\000\002\011\006\000\002\011\006" +
    "\000\002\011\010\000\002\045\002\000\002\006\007\000" +
    "\002\006\005\000\002\006\006\000\002\006\005\000\002" +
    "\021\007\000\002\021\006\000\002\021\007\000\002\025" +
    "\007\000\002\025\006\000\002\024\004\000\002\024\003" +
    "\000\002\023\005\000\002\023\005\000\002\023\005\000" +
    "\002\023\005\000\002\023\005\000\002\023\005\000\002" +
    "\023\005\000\002\023\005\000\002\023\005\000\002\023" +
    "\004\000\002\046\002\000\002\023\006\000\002\023\003" +
    "\000\002\023\003\000\002\023\003\000\002\023\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\235\000\006\017\ufff6\047\ufff6\001\002\000\006\017" +
    "\ufffe\047\ufffe\001\002\000\004\002\001\001\002\000\004" +
    "\002\007\001\002\000\004\002\000\001\002\000\006\017" +
    "\013\047\012\001\002\000\006\017\uffff\047\uffff\001\002" +
    "\000\010\024\032\025\020\053\206\001\002\000\004\020" +
    "\014\001\002\000\024\021\ufff5\022\ufff5\023\ufff5\024\ufff5" +
    "\025\ufff5\031\ufff5\037\ufff5\045\ufff5\053\ufff5\001\002\000" +
    "\024\021\ufff2\022\ufff2\023\ufff2\024\ufff2\025\ufff2\031\ufff2" +
    "\037\ufff2\045\ufff2\053\ufff2\001\002\000\024\021\035\022" +
    "\017\023\031\024\032\025\020\031\034\037\024\045\042" +
    "\053\025\001\002\000\004\053\203\001\002\000\004\053" +
    "\uffda\001\002\000\004\053\167\001\002\000\040\021\ufff3" +
    "\022\ufff3\023\ufff3\024\ufff3\025\ufff3\031\ufff3\034\ufff3\035" +
    "\ufff3\037\ufff3\044\ufff3\045\ufff3\046\ufff3\051\ufff3\052\ufff3" +
    "\053\ufff3\001\002\000\006\036\163\053\103\001\002\000" +
    "\004\053\150\001\002\000\010\010\130\012\110\036\127" +
    "\001\002\000\040\021\ufff1\022\ufff1\023\ufff1\024\ufff1\025" +
    "\ufff1\031\ufff1\034\ufff1\035\ufff1\037\ufff1\044\ufff1\045\ufff1" +
    "\046\ufff1\051\ufff1\052\ufff1\053\ufff1\001\002\000\040\021" +
    "\uffeb\022\uffeb\023\uffeb\024\uffeb\025\uffeb\031\uffeb\034\uffeb" +
    "\035\uffeb\037\uffeb\044\uffeb\045\uffeb\046\uffeb\051\uffeb\052" +
    "\uffeb\053\uffeb\001\002\000\040\021\uffed\022\uffed\023\uffed" +
    "\024\uffed\025\uffed\031\uffed\034\uffed\035\uffed\037\uffed\044" +
    "\uffed\045\uffed\046\uffed\051\uffed\052\uffed\053\uffed\001\002" +
    "\000\014\010\050\030\044\053\043\054\045\055\047\001" +
    "\002\000\004\053\uffdb\001\002\000\040\021\ufff0\022\ufff0" +
    "\023\ufff0\024\ufff0\025\ufff0\031\ufff0\034\ufff0\035\ufff0\037" +
    "\ufff0\044\ufff0\045\ufff0\046\ufff0\051\ufff0\052\ufff0\053\ufff0" +
    "\001\002\000\014\010\050\030\044\053\043\054\045\055" +
    "\047\001\002\000\004\002\ufff4\001\002\000\040\021\uffea" +
    "\022\uffea\023\uffea\024\uffea\025\uffea\031\uffea\034\uffea\035" +
    "\uffea\037\uffea\044\uffea\045\uffea\046\uffea\051\uffea\052\uffea" +
    "\053\uffea\001\002\000\040\021\uffec\022\uffec\023\uffec\024" +
    "\uffec\025\uffec\031\uffec\034\uffec\035\uffec\037\uffec\044\uffec" +
    "\045\uffec\046\uffec\051\uffec\052\uffec\053\uffec\001\002\000" +
    "\040\021\uffee\022\uffee\023\uffee\024\uffee\025\uffee\031\uffee" +
    "\034\uffee\035\uffee\037\uffee\044\uffee\045\uffee\046\uffee\051" +
    "\uffee\052\uffee\053\uffee\001\002\000\040\021\uffef\022\uffef" +
    "\023\uffef\024\uffef\025\uffef\031\uffef\034\uffef\035\uffef\037" +
    "\uffef\044\uffef\045\uffef\046\uffef\051\uffef\052\uffef\053\uffef" +
    "\001\002\000\014\010\050\030\044\053\043\054\045\055" +
    "\047\001\002\000\050\004\uffbb\005\uffbb\006\uffbb\007\uffbb" +
    "\010\uffbb\011\uffbb\012\110\014\uffbb\015\uffbb\016\uffbb\026" +
    "\uffbb\027\uffbb\030\uffbb\032\uffbb\033\uffbb\043\uffbb\053\uffbb" +
    "\054\uffbb\055\uffbb\001\002\000\014\010\050\030\044\053" +
    "\043\054\045\055\047\001\002\000\046\004\uffb9\005\uffb9" +
    "\006\uffb9\007\uffb9\010\uffb9\011\uffb9\014\uffb9\015\uffb9\016" +
    "\uffb9\026\uffb9\027\uffb9\030\uffb9\032\uffb9\033\uffb9\043\uffb9" +
    "\053\uffb9\054\uffb9\055\uffb9\001\002\000\046\004\uffba\005" +
    "\uffba\006\uffba\007\uffba\010\uffba\011\uffba\014\uffba\015\uffba" +
    "\016\uffba\026\uffba\027\uffba\030\uffba\032\uffba\033\uffba\043" +
    "\uffba\053\103\054\uffba\055\uffba\001\002\000\046\004\uffb8" +
    "\005\uffb8\006\uffb8\007\uffb8\010\uffb8\011\uffb8\014\uffb8\015" +
    "\uffb8\016\uffb8\026\uffb8\027\uffb8\030\uffb8\032\uffb8\033\uffb8" +
    "\043\uffb8\053\uffb8\054\uffb8\055\uffb8\001\002\000\014\010" +
    "\050\030\044\053\043\054\045\055\047\001\002\000\026" +
    "\004\055\005\052\006\060\007\053\014\062\015\054\016" +
    "\056\026\063\027\061\043\057\001\002\000\014\010\050" +
    "\030\044\053\043\054\045\055\047\001\002\000\014\010" +
    "\050\030\044\053\043\054\045\055\047\001\002\000\014" +
    "\010\050\030\044\053\043\054\045\055\047\001\002\000" +
    "\014\010\050\030\044\053\043\054\045\055\047\001\002" +
    "\000\014\010\050\030\044\053\043\054\045\055\047\001" +
    "\002\000\024\022\uffdf\023\uffdf\024\uffdf\025\uffdf\031\uffdf" +
    "\037\uffdf\045\uffdf\046\uffdf\053\uffdf\001\002\000\014\010" +
    "\050\030\044\053\043\054\045\055\047\001\002\000\014" +
    "\010\050\030\044\053\043\054\045\055\047\001\002\000" +
    "\014\010\050\030\044\053\043\054\045\055\047\001\002" +
    "\000\014\010\050\030\044\053\043\054\045\055\047\001" +
    "\002\000\046\004\uffc0\005\uffc0\006\uffc0\007\uffc0\010\uffc0" +
    "\011\uffc0\014\uffc0\015\uffc0\016\uffc0\026\uffc0\027\uffc0\030" +
    "\uffc0\032\uffc0\033\uffc0\043\uffc0\053\uffc0\054\uffc0\055\uffc0" +
    "\001\002\000\046\004\055\005\052\006\060\007\053\010" +
    "\uffc3\011\uffc3\014\uffc3\015\054\016\056\026\063\027\061" +
    "\030\uffc3\032\uffc3\033\uffc3\043\uffc3\053\uffc3\054\uffc3\055" +
    "\uffc3\001\002\000\046\004\uffbf\005\uffbf\006\uffbf\007\uffbf" +
    "\010\uffbf\011\uffbf\014\uffbf\015\uffbf\016\uffbf\026\uffbf\027" +
    "\uffbf\030\uffbf\032\uffbf\033\uffbf\043\uffbf\053\uffbf\054\uffbf" +
    "\055\uffbf\001\002\000\046\004\uffc5\005\uffc5\006\uffc5\007" +
    "\uffc5\010\uffc5\011\uffc5\014\uffc5\015\uffc5\016\uffc5\026\063" +
    "\027\061\030\uffc5\032\uffc5\033\uffc5\043\uffc5\053\uffc5\054" +
    "\uffc5\055\uffc5\001\002\000\024\022\ufff2\023\ufff2\024\ufff2" +
    "\025\ufff2\031\ufff2\037\ufff2\045\ufff2\046\ufff2\053\ufff2\001" +
    "\002\000\024\022\017\023\031\024\032\025\020\031\034" +
    "\037\024\045\042\046\072\053\025\001\002\000\040\021" +
    "\uffde\022\uffde\023\uffde\024\uffde\025\uffde\031\uffde\034\uffde" +
    "\035\uffde\037\uffde\044\uffde\045\uffde\046\uffde\051\uffde\052" +
    "\uffde\053\uffde\001\002\000\046\004\055\005\052\006\060" +
    "\007\053\010\uffc1\011\uffc1\014\uffc1\015\uffc1\016\uffc1\026" +
    "\063\027\061\030\uffc1\032\uffc1\033\uffc1\043\uffc1\053\uffc1" +
    "\054\uffc1\055\uffc1\001\002\000\046\004\uffc7\005\uffc7\006" +
    "\060\007\053\010\uffc7\011\uffc7\014\uffc7\015\uffc7\016\uffc7" +
    "\026\063\027\061\030\uffc7\032\uffc7\033\uffc7\043\uffc7\053" +
    "\uffc7\054\uffc7\055\uffc7\001\002\000\046\004\055\005\052" +
    "\006\060\007\053\010\uffc2\011\uffc2\014\uffc2\015\uffc2\016" +
    "\uffc2\026\063\027\061\030\uffc2\032\uffc2\033\uffc2\043\uffc2" +
    "\053\uffc2\054\uffc2\055\uffc2\001\002\000\046\004\uffc4\005" +
    "\uffc4\006\uffc4\007\uffc4\010\uffc4\011\uffc4\014\uffc4\015\uffc4" +
    "\016\uffc4\026\063\027\061\030\uffc4\032\uffc4\033\uffc4\043" +
    "\uffc4\053\uffc4\054\uffc4\055\uffc4\001\002\000\046\004\uffc6" +
    "\005\uffc6\006\060\007\053\010\uffc6\011\uffc6\014\uffc6\015" +
    "\uffc6\016\uffc6\026\063\027\061\030\uffc6\032\uffc6\033\uffc6" +
    "\043\uffc6\053\uffc6\054\uffc6\055\uffc6\001\002\000\026\004" +
    "\055\005\052\006\060\007\053\011\uffbd\014\062\015\054" +
    "\016\056\026\063\027\061\001\002\000\004\011\102\001" +
    "\002\000\046\004\uffbc\005\uffbc\006\uffbc\007\uffbc\010\uffbc" +
    "\011\uffbc\014\uffbc\015\uffbc\016\uffbc\026\uffbc\027\uffbc\030" +
    "\uffbc\032\uffbc\033\uffbc\043\uffbc\053\uffbc\054\uffbc\055\uffbc" +
    "\001\002\000\004\012\104\001\002\000\004\054\105\001" +
    "\002\000\004\013\106\001\002\000\054\004\uffcb\005\uffcb" +
    "\006\uffcb\007\uffcb\010\uffcb\011\uffcb\014\uffcb\015\uffcb\016" +
    "\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\030\uffcb\032\uffcb" +
    "\033\uffcb\036\uffcb\043\uffcb\053\uffcb\054\uffcb\055\uffcb\001" +
    "\002\000\046\004\uffbe\005\uffbe\006\uffbe\007\uffbe\010\uffbe" +
    "\011\uffbe\014\uffbe\015\uffbe\016\uffbe\026\uffbe\027\uffbe\030" +
    "\uffbe\032\uffbe\033\uffbe\043\uffbe\053\uffbe\054\uffbe\055\uffbe" +
    "\001\002\000\004\054\111\001\002\000\004\013\112\001" +
    "\002\000\054\004\uffca\005\uffca\006\uffca\007\uffca\010\uffca" +
    "\011\uffca\014\uffca\015\uffca\016\uffca\024\uffca\025\uffca\026" +
    "\uffca\027\uffca\030\uffca\032\uffca\033\uffca\036\uffca\043\uffca" +
    "\053\uffca\054\uffca\055\uffca\001\002\000\026\004\055\005" +
    "\052\006\060\007\053\014\062\015\054\016\056\026\063" +
    "\027\061\033\uffe5\001\002\000\004\033\115\001\002\000" +
    "\024\022\uffe4\023\uffe4\024\uffe4\025\uffe4\031\uffe4\034\uffe4" +
    "\037\uffe4\045\uffe4\053\uffe4\001\002\000\024\022\ufff2\023" +
    "\ufff2\024\ufff2\025\ufff2\031\ufff2\034\ufff2\037\ufff2\045\ufff2" +
    "\053\ufff2\001\002\000\024\022\017\023\031\024\032\025" +
    "\020\031\034\034\120\037\024\045\042\053\025\001\002" +
    "\000\024\022\uffe3\023\uffe3\024\uffe3\025\uffe3\031\uffe3\035" +
    "\uffe3\037\uffe3\045\uffe3\053\uffe3\001\002\000\024\022\ufff2" +
    "\023\ufff2\024\ufff2\025\ufff2\031\ufff2\035\ufff2\037\ufff2\045" +
    "\ufff2\053\ufff2\001\002\000\024\022\017\023\031\024\032" +
    "\025\020\031\034\035\123\037\024\045\042\053\025\001" +
    "\002\000\040\021\uffe2\022\uffe2\023\uffe2\024\uffe2\025\uffe2" +
    "\031\uffe2\034\uffe2\035\uffe2\037\uffe2\044\uffe2\045\uffe2\046" +
    "\uffe2\051\uffe2\052\uffe2\053\uffe2\001\002\000\026\004\055" +
    "\005\052\006\060\007\053\014\062\015\054\016\056\026" +
    "\063\027\061\032\uffe9\001\002\000\004\032\126\001\002" +
    "\000\040\021\uffe8\022\uffe8\023\uffe8\024\uffe8\025\uffe8\031" +
    "\uffe8\034\uffe8\035\uffe8\037\uffe8\044\uffe8\045\uffe8\046\uffe8" +
    "\051\uffe8\052\uffe8\053\uffe8\001\002\000\014\010\050\030" +
    "\044\053\143\054\045\055\047\001\002\000\016\010\050" +
    "\011\133\030\044\053\043\054\045\055\047\001\002\000" +
    "\040\004\uffba\005\uffba\006\uffba\007\uffba\010\uffba\011\141" +
    "\014\uffba\015\uffba\016\uffba\026\uffba\027\uffba\030\uffba\053" +
    "\103\054\uffba\055\uffba\001\002\000\016\010\050\011\136" +
    "\030\044\053\043\054\045\055\047\001\002\000\004\032" +
    "\135\001\002\000\040\004\055\005\052\006\060\007\053" +
    "\010\uffc8\011\uffc8\014\062\015\054\016\056\026\063\027" +
    "\061\030\uffc8\053\uffc8\054\uffc8\055\uffc8\001\002\000\040" +
    "\021\uffcd\022\uffcd\023\uffcd\024\uffcd\025\uffcd\031\uffcd\034" +
    "\uffcd\035\uffcd\037\uffcd\044\uffcd\045\uffcd\046\uffcd\051\uffcd" +
    "\052\uffcd\053\uffcd\001\002\000\004\032\140\001\002\000" +
    "\040\004\055\005\052\006\060\007\053\010\uffc9\011\uffc9" +
    "\014\062\015\054\016\056\026\063\027\061\030\uffc9\053" +
    "\uffc9\054\uffc9\055\uffc9\001\002\000\040\021\uffce\022\uffce" +
    "\023\uffce\024\uffce\025\uffce\031\uffce\034\uffce\035\uffce\037" +
    "\uffce\044\uffce\045\uffce\046\uffce\051\uffce\052\uffce\053\uffce" +
    "\001\002\000\004\032\142\001\002\000\040\021\uffcc\022" +
    "\uffcc\023\uffcc\024\uffcc\025\uffcc\031\uffcc\034\uffcc\035\uffcc" +
    "\037\uffcc\044\uffcc\045\uffcc\046\uffcc\051\uffcc\052\uffcc\053" +
    "\uffcc\001\002\000\032\004\uffbb\005\uffbb\006\uffbb\007\uffbb" +
    "\010\130\012\110\014\uffbb\015\uffbb\016\uffbb\026\uffbb\027" +
    "\uffbb\032\uffbb\001\002\000\026\004\055\005\052\006\060" +
    "\007\053\014\062\015\054\016\056\026\063\027\061\032" +
    "\uffd3\001\002\000\040\021\uffd1\022\uffd1\023\uffd1\024\uffd1" +
    "\025\uffd1\031\uffd1\034\uffd1\035\uffd1\037\uffd1\044\uffd1\045" +
    "\uffd1\046\uffd1\051\uffd1\052\uffd1\053\uffd1\001\002\000\004" +
    "\032\147\001\002\000\040\021\uffd2\022\uffd2\023\uffd2\024" +
    "\uffd2\025\uffd2\031\uffd2\034\uffd2\035\uffd2\037\uffd2\044\uffd2" +
    "\045\uffd2\046\uffd2\051\uffd2\052\uffd2\053\uffd2\001\002\000" +
    "\004\040\151\001\002\000\004\054\152\001\002\000\004" +
    "\041\153\001\002\000\004\054\154\001\002\000\004\042" +
    "\155\001\002\000\004\054\156\001\002\000\004\043\157" +
    "\001\002\000\024\022\uffe1\023\uffe1\024\uffe1\025\uffe1\031" +
    "\uffe1\037\uffe1\044\uffe1\045\uffe1\053\uffe1\001\002\000\024" +
    "\022\ufff2\023\ufff2\024\ufff2\025\ufff2\031\ufff2\037\ufff2\044" +
    "\ufff2\045\ufff2\053\ufff2\001\002\000\024\022\017\023\031" +
    "\024\032\025\020\031\034\037\024\044\162\045\042\053" +
    "\025\001\002\000\040\021\uffe0\022\uffe0\023\uffe0\024\uffe0" +
    "\025\uffe0\031\uffe0\034\uffe0\035\uffe0\037\uffe0\044\uffe0\045" +
    "\uffe0\046\uffe0\051\uffe0\052\uffe0\053\uffe0\001\002\000\014" +
    "\010\050\030\044\053\143\054\045\055\047\001\002\000" +
    "\026\004\055\005\052\006\060\007\053\014\062\015\054" +
    "\016\056\026\063\027\061\032\166\001\002\000\040\021" +
    "\uffcf\022\uffcf\023\uffcf\024\uffcf\025\uffcf\031\uffcf\034\uffcf" +
    "\035\uffcf\037\uffcf\044\uffcf\045\uffcf\046\uffcf\051\uffcf\052" +
    "\uffcf\053\uffcf\001\002\000\040\021\uffd0\022\uffd0\023\uffd0" +
    "\024\uffd0\025\uffd0\031\uffd0\034\uffd0\035\uffd0\037\uffd0\044" +
    "\uffd0\045\uffd0\046\uffd0\051\uffd0\052\uffd0\053\uffd0\001\002" +
    "\000\010\012\171\032\uffd7\036\170\001\002\000\014\010" +
    "\050\030\044\053\143\054\045\055\047\001\002\000\004" +
    "\054\174\001\002\000\004\032\173\001\002\000\040\021" +
    "\uffd6\022\uffd6\023\uffd6\024\uffd6\025\uffd6\031\uffd6\034\uffd6" +
    "\035\uffd6\037\uffd6\044\uffd6\045\uffd6\046\uffd6\051\uffd6\052" +
    "\uffd6\053\uffd6\001\002\000\004\013\175\001\002\000\004" +
    "\032\176\001\002\000\040\021\uffd4\022\uffd4\023\uffd4\024" +
    "\uffd4\025\uffd4\031\uffd4\034\uffd4\035\uffd4\037\uffd4\044\uffd4" +
    "\045\uffd4\046\uffd4\051\uffd4\052\uffd4\053\uffd4\001\002\000" +
    "\026\004\055\005\052\006\060\007\053\014\062\015\054" +
    "\016\056\026\063\027\061\032\uffd9\001\002\000\040\021" +
    "\uffd5\022\uffd5\023\uffd5\024\uffd5\025\uffd5\031\uffd5\034\uffd5" +
    "\035\uffd5\037\uffd5\044\uffd5\045\uffd5\046\uffd5\051\uffd5\052" +
    "\uffd5\053\uffd5\001\002\000\004\032\202\001\002\000\040" +
    "\021\uffd8\022\uffd8\023\uffd8\024\uffd8\025\uffd8\031\uffd8\034" +
    "\uffd8\035\uffd8\037\uffd8\044\uffd8\045\uffd8\046\uffd8\051\uffd8" +
    "\052\uffd8\053\uffd8\001\002\000\004\032\uffe7\001\002\000" +
    "\004\032\205\001\002\000\040\021\uffe6\022\uffe6\023\uffe6" +
    "\024\uffe6\025\uffe6\031\uffe6\034\uffe6\035\uffe6\037\uffe6\044" +
    "\uffe6\045\uffe6\046\uffe6\051\uffe6\052\uffe6\053\uffe6\001\002" +
    "\000\004\010\232\001\002\000\004\053\210\001\002\000" +
    "\004\010\ufffd\001\002\000\004\010\212\001\002\000\010" +
    "\011\ufff7\024\ufff9\025\ufff9\001\002\000\006\024\032\025" +
    "\020\001\002\000\004\011\215\001\002\000\004\050\216" +
    "\001\002\000\024\022\ufffc\023\ufffc\024\ufffc\025\ufffc\031" +
    "\ufffc\037\ufffc\045\ufffc\052\ufffc\053\ufffc\001\002\000\024" +
    "\022\ufff2\023\ufff2\024\ufff2\025\ufff2\031\ufff2\037\ufff2\045" +
    "\ufff2\052\ufff2\053\ufff2\001\002\000\024\022\017\023\031" +
    "\024\032\025\020\031\034\037\024\045\042\052\221\053" +
    "\025\001\002\000\014\010\050\030\044\053\043\054\045" +
    "\055\047\001\002\000\026\004\055\005\052\006\060\007" +
    "\053\014\062\015\054\016\056\026\063\027\061\032\223" +
    "\001\002\000\004\051\224\001\002\000\006\017\ufffb\047" +
    "\ufffb\001\002\000\004\053\230\001\002\000\010\011\ufff7" +
    "\024\ufff9\025\ufff9\001\002\000\004\011\ufff8\001\002\000" +
    "\012\011\uffdd\012\110\024\uffdd\025\uffdd\001\002\000\012" +
    "\011\uffdc\024\uffdc\025\uffdc\053\103\001\002\000\010\011" +
    "\ufff7\024\ufff9\025\ufff9\001\002\000\004\011\234\001\002" +
    "\000\004\050\235\001\002\000\024\022\ufff2\023\ufff2\024" +
    "\ufff2\025\ufff2\031\ufff2\037\ufff2\045\ufff2\051\ufff2\053\ufff2" +
    "\001\002\000\024\022\017\023\031\024\032\025\020\031" +
    "\034\037\024\045\042\051\237\053\025\001\002\000\006" +
    "\017\ufffa\047\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\235\000\010\002\005\003\004\032\003\001\001\000" +
    "\004\017\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\020\010\001\001\000\002\001" +
    "\001\000\004\026\206\001\001\000\002\001\001\000\004" +
    "\033\014\001\001\000\004\004\015\001\001\000\030\005" +
    "\021\006\032\007\040\010\037\011\025\012\027\013\036" +
    "\014\026\021\035\025\022\026\020\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\023\123\025\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\023\112\025\045\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\023\050\025\045\001\001\000\002" +
    "\001\001\000\006\023\106\025\045\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\023\077" +
    "\025\045\001\001\000\002\001\001\000\006\023\076\025" +
    "\045\001\001\000\006\023\075\025\045\001\001\000\006" +
    "\023\074\025\045\001\001\000\006\023\073\025\045\001" +
    "\001\000\006\023\072\025\045\001\001\000\004\042\067" +
    "\001\001\000\006\023\066\025\045\001\001\000\006\023" +
    "\065\025\045\001\001\000\006\023\064\025\045\001\001" +
    "\000\006\023\063\025\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\070\001\001\000\030\005\021\006\032\007\040\010" +
    "\037\011\025\012\027\013\036\014\026\021\035\025\022" +
    "\026\020\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\046\100\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\036\113" +
    "\001\001\000\002\001\001\000\004\037\115\001\001\000" +
    "\004\004\116\001\001\000\030\005\021\006\032\007\040" +
    "\010\037\011\025\012\027\013\036\014\026\021\035\025" +
    "\022\026\020\001\001\000\004\040\120\001\001\000\004" +
    "\004\121\001\001\000\030\005\021\006\032\007\040\010" +
    "\037\011\025\012\027\013\036\014\026\021\035\025\022" +
    "\026\020\001\001\000\002\001\001\000\004\034\124\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\021\144" +
    "\023\143\025\045\001\001\000\010\023\133\024\131\025" +
    "\130\001\001\000\002\001\001\000\006\023\136\025\045" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\045\145\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\041\157\001\001\000" +
    "\004\004\160\001\001\000\030\005\021\006\032\007\040" +
    "\010\037\011\025\012\027\013\036\014\026\021\035\025" +
    "\022\026\020\001\001\000\002\001\001\000\010\021\164" +
    "\023\163\025\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\044\171\001\001\000\010" +
    "\021\177\023\176\025\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\043\200\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\035\203\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\027\210\001\001" +
    "\000\002\001\001\000\006\015\213\031\212\001\001\000" +
    "\006\016\225\026\224\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\030\216\001\001\000\004\004\217\001" +
    "\001\000\030\005\021\006\032\007\040\010\037\011\025" +
    "\012\027\013\036\014\026\021\035\025\022\026\020\001" +
    "\001\000\006\023\221\025\045\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\025\230\001" +
    "\001\000\006\015\226\031\212\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\015\232\031" +
    "\212\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\235\001\001\000\030\005\021\006\032\007\040\010" +
    "\037\011\025\012\027\013\036\014\026\021\035\025\022" +
    "\026\020\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




  //classe para permitir salvar tipo do token e o valor.
  class table_symbol {

       private String tipo;
       private String valor;

       table_symbol(String tipo, String valor){
          this.tipo = tipo;
          this.valor = valor;
       }

         table_symbol(String tipo){
          this.tipo = tipo;
       }

       public String getTipo(){
          return tipo;
       }

       public String getValor(){
          return valor;
       }

       public void setValor(String valor){
          this.valor = valor;
       }

  }

/** table of declared symbols -- contains production parts indexed by name */
   private Hashtable<String, table_symbol> symT = new Hashtable<String, table_symbol>();
   private static final String LEFT_PAR = "(";
   private static final String RIGHT_PAR = ")";
   private int POS = 0;
   private int flag = 0;
    /* Change the method report_error so it will display the line and
       column of where the error occurred in the input as well as the
       reason for the error which is passed into the method in the
       String 'message'. */
    public void report_error(String message, Object info) {
   
        /* Create a StringBuilder called 'm' with the string 'Error' in it. */
        StringBuilder m = new StringBuilder("Error");
   
        /* Check if the information passed to the method is the same
           type as the type java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the
               information in the object info that is being typecasted
               as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            /* Check if the line number in the input is greater or
               equal to zero. */
            if (s.left >= 0) {                
                /* Add to the end of the StringBuilder error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuilder error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }
   
        /* Add to the end of the StringBuilder error message created in
           this method the message that was passed into this method. */
        m.append(" : "+message);
   
        /* Print the contents of the StringBuilder 'm', which contains
           an error message, out on a line. */
        System.err.println(m);
    }
   
    /* Change the method report_fatal_error so when it reports a fatal
       error it will display the line and column number of where the
       fatal error occurred in the input as well as the reason for the
       fatal error which is passed into the method in the object
       'message' and then exit.*/
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

    public void format_code(){
       for(int i=0; i < POS * 3; i++){
          System.out.print(" ");
       }
    }

    
    public void update_symT(String id, String valor){

       table_symbol t = symT.get(id);
       t.setValor(valor);
       symT.replace(id,t);

    }

    public String check_expr(String e1, String e2){

      String res;
      
      if(! symT.containsKey(e1)) {
           report_fatal_error("Variavel nao declarada: " + e1, null);
      }   

      if(e2 == null){
         table_symbol te1 = symT.get(e1);
         String tp1 = te1.getTipo();
         res = tp1;
      } else {

         if(! symT.containsKey(e2)) {
           report_fatal_error("Variavel nao declarada: " + e1, null);
         }
         
         table_symbol te1 = symT.get(e1);
         table_symbol te2 = symT.get(e2);

         String tp1 = te1.getTipo();
         String tp2 = te2.getTipo();

         if(tp1.equals(tp2)){
           res = tp1;
         } else {
           res =  "FLOAT";
         }
      }
      return "FLOAT";
    }



    /**************** emit code *****************/

    public void emit_program(){

       System.out.print("#include<stdio.h>\n");
       System.out.print("#include<stdlib.h>\n\n");

    }

    public void emit_startprogram(){

       System.out.print("int main(){\n");

    }

 
     public void emit_endprg(){

       System.out.print("}\n");

    }

     public void emit_return(){

       System.out.print("return 0;\n");

    }

    public void emit_semi(){
        System.out.print(";\n");
    }

    public void emit_declare_variable_with_value(String id, String value, String tipo){

       if(symT.containsKey(id)){
          report_fatal_error("Variável duplicada [" + id + "]",null);
       }
       symT.put(id,new table_symbol(tipo,value));
       System.out.print(id + "=" + value); 
              
    }

    public void emit_declare_variable_without_value(String id, String tipo){

      if(symT.containsKey(id)){
          report_fatal_error("Variável duplicada [" + id + "]",null);
       } 

       symT.put(id,new table_symbol(tipo));
       System.out.print(id); 
    }

    public void emit_assign_id_expr(String id, String value){
      
       if(! symT.containsKey(id)) {
           report_fatal_error("Variavel nao declarada: " + id, null);
      } else {    

            System.out.print(id + "=" + value); 
            update_symT(id,value);
      }
  

    }
    
    public void emit_if(String e){

       System.out.print("if(" + e + ")");
    }


    public void emit_escreva(String id){

      if(! symT.containsKey(id)) {
           report_fatal_error("Variavel nao declarada: " + id, null);
      } else {    

         String tipo = (symT.get(id)).getTipo();

         if(tipo.equals("INT")) {
            System.out.print("printf(\"\\n%d\"," + id + ")") ;
         } else {
            System.out.print("printf(\"\\n%f\"," + id + ")");
         }   
      }
    }

        public void emit_leia(String id){

      if(! symT.containsKey(id)) {
           report_fatal_error("Variavel nao declarada: " + id, null);
      } else {    
         String tipo = (symT.get(id)).getTipo();

         if(tipo.equals("INT")) {
            System.out.print("scanf(\"%d\",&" + id + ")");
         } else {
            System.out.print("scanf(\"%f\",&" + id + ")");
         }   
      }
    }

    public void emit_for(String id, String i1, String i2, String i3){
       System.out.print("for(" + id + "=" + i1 + ";" + id + "<" + i2 + ";" + id + "+=" + i3 + "){\n" );
    }

    public void emit_else(){
       System.out.print("else{\n");
    }

    public void emit_while(String e){
      System.out.print("while(" + e + "){\n");     
    }

    public void emit_vector(String id, String num){

      System.out.print(id + "[" + num + "];\n");

    }

    public void emit_func(String id, String e){
       System.out.print(id + "(" + e +");\n");
    }

    public void emit_inteiro(){
       System.out.print("int ");
    }

    public void emit_flutuante(){
       System.out.print("float ");
    }

    public void emit_declare_vector(String t, String id, String i){

      if(symT.containsKey(id)){
          report_fatal_error("Variável duplicada [" + id + "]",null);
      } 

      symT.put(id,new table_symbol(t));
      System.out.print(id + "["+i+"]");

    }

    public String check_id( String id, String i){

      if(! symT.containsKey(id)){
          report_fatal_error("Variável Não declarada [" + id + "]",null);
      } 

      symT.put(id+"["+i+"]",new table_symbol("TANTOFAZ"));
      
      return id+"["+i+"]";

    }

    public void emit_assign_vector(String v, String e){
       System.out.print(v+"="+e+";\n");
    }

   public String filtro(String v){

      if(symT.containsKey(v)){
         return v;
      } 

      symT.put(v,new table_symbol("vetor"));

      return v;
   }

   public void declare_param(String t, String id){

      symT.put(id,new table_symbol(t));
   }




/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // s ::= program 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= s EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // listafuncao ::= listafuncao func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listafuncao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listafuncao ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listafuncao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$0 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 System.out.print(id+"("); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$1 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
 System.out.println("){"); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // func ::= FUNCAO tipo ID NT$0 LPAREN list_param RPAREN STARTFUNC NT$1 list_command RETORNO expr SEMI ENDFUNC 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-11)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 format_code(); System.out.println("return " + value + ";\n}\n"); POS--; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // func ::= FUNCAO ID LPAREN list_param RPAREN STARTFUNC list_command ENDFUNC 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // NT$2 ::= 
            {
              Object RESULT =null;
 if(flag != 0) System.out.print(","); flag = 1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // list_param ::= NT$2 param list_param 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // list_param ::= 
            {
              Object RESULT =null;
		 flag = 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$3 ::= 
            {
              Object RESULT =null;
 emit_program();               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // NT$4 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
 emit_startprogram() ; POS++;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // program ::= NT$3 listafuncao PROGRAM STARTPRG NT$4 list_command ENDPRG 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 format_code(); emit_return(); POS--; format_code(); emit_endprg() ;        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // list_command ::= list_command command 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_command",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // list_command ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_command",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // command ::= declare_variable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // command ::= assign 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // command ::= writel 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // command ::= readl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // command ::= iff 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // command ::= for 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // command ::= while 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // command ::= chamafunc 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 format_code(); System.out.println(f+";");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // NT$5 ::= 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_escreva(value);  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$5",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // writel ::= WRITELINE expr NT$5 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi();          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("writel",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // NT$6 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_leia(id);   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$6",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // readl ::= READLINE ID NT$6 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi();     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("readl",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // NT$7 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_if(e);  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$7",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT$8 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
 System.out.println("{"); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$8",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // NT$9 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
 POS--; format_code(); emit_endprg(); format_code(); emit_else(); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$9",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // iff ::= IFF expr NT$7 THENN NT$8 list_command ELSEE NT$9 list_command ENDELSE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$9
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		POS--; format_code(); System.out.print("}\n"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("iff",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // NT$10 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int i1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String i1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String i2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int i3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int i3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i3 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 format_code(); emit_for(id,i1,i2,i3); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$10",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // for ::= PARA ID DE INTT ATE INTT PASSO INTT FACA NT$10 list_command FIMPARA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$10
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-10)).value;
		int i1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		String i1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String i2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int i3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int i3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String i3 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 POS--; format_code(); emit_endprg(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("for",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // NT$11 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 format_code(); emit_while(e); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$11",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // while ::= ENQUANTO expr FACA NT$11 list_command FIMENQUANTO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$11
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 POS--; format_code(); emit_endprg(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // param ::= tipo ID 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 declare_param(t,id); System.out.print(id+" "); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // param ::= tipo vetor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // tipo ::= DECLINT 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = "INT"  ; format_code();  emit_inteiro();   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // tipo ::= DECLFLOAT 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = "FLOAT"; format_code();  emit_flutuante(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // NT$12 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 emit_declare_variable_with_value(id,value,t);  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$12",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // declare_variable ::= tipo ID ATTRIB expr NT$12 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$12
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // NT$13 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 emit_declare_variable_without_value(id,t); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$13",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // declare_variable ::= tipo ID NT$13 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$13
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi();  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // declare_variable ::= tipo ID ATTRIB chamafunc 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 emit_declare_variable_without_value(id,t); System.out.print("=" +f+";\n"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // declare_variable ::= tipo ID LBRCKT INTT RBRCKT SEMI 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_declare_vector(t,id,i); emit_semi(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // NT$14 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_assign_id_expr(id,value); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$14",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // assign ::= ID ATTRIB expr NT$14 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$14
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // assign ::= ID ATTRIB chamafunc 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // assign ::= vetor ATTRIB expr SEMI 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 format_code(); emit_assign_vector(v,e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // assign ::= vetor ATTRIB chamafunc 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // chamafunc ::= ID LPAREN expr_list RPAREN SEMI 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = id + "("+ e +")"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chamafunc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // chamafunc ::= ID LPAREN RPAREN SEMI 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		 RESULT = id + "()"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chamafunc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // chamafunc ::= ID LPAREN vetor RPAREN SEMI 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = id+"(" + v + ")";
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chamafunc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // vetor ::= vetor ID LBRCKT INTT RBRCKT 
            {
              String RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(v!=null) RESULT = v + ", " + id+"["+i+"]"; else RESULT = id+"["+i+"]"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vetor",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // vetor ::= ID LBRCKT INTT RBRCKT 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = id+"["+i+"]"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vetor",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr_list ::= expr_list expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = e1 +","+ e;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr_list ::= expr 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = e;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= expr PLUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "+" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= expr MINUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "-" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= expr TIMES expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "*" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= expr DIVIDE expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "/" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= expr EQUALS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "==" + e2; symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= expr GREATER expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + ">" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= expr LESS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "<" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= expr E expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "&&" + e2; symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= expr OU expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "||" + e2; symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr ::= NAO expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =   "!" + e1;  symT.put(RESULT,new table_symbol(check_expr(e1,null),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // NT$15 ::= 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 RESULT =  "(" + e1  + ")";symT.put(RESULT,new table_symbol(check_expr(e1,null),RESULT)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$15",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expr ::= LPAREN expr NT$15 RPAREN 
            {
              String RESULT =null;
              // propagate RESULT from NT$15
                RESULT = (String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expr ::= ID 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = i;                                                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expr ::= vetor 
            {
              String RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = filtro(v);                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expr ::= INTT 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n;  symT.put(n,new table_symbol("INT",n));                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expr ::= FLOATT 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n;  symT.put(n,new table_symbol("FLOAT",n));                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
