
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.util.Stack;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141204 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\117\000\002\002\004\000\002\002\004\000\002\017" +
    "\004\000\002\017\002\000\002\020\016\000\002\020\012" +
    "\000\002\015\004\000\002\015\002\000\002\030\002\000" +
    "\002\031\002\000\002\003\010\000\002\004\004\000\002" +
    "\004\002\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\005\003\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\032\002\000" +
    "\002\007\006\000\002\033\002\000\002\010\006\000\002" +
    "\034\002\000\002\035\002\000\002\036\002\000\002\012" +
    "\014\000\002\037\002\000\002\013\016\000\002\040\002" +
    "\000\002\014\010\000\002\016\004\000\002\016\004\000" +
    "\002\027\003\000\002\027\003\000\002\041\002\000\002" +
    "\011\010\000\002\042\002\000\002\011\006\000\002\043" +
    "\002\000\002\011\007\000\002\011\010\000\002\044\002" +
    "\000\002\006\007\000\002\006\005\000\002\006\006\000" +
    "\002\006\006\000\002\045\002\000\002\046\002\000\002" +
    "\021\011\000\002\047\002\000\002\021\007\000\002\021" +
    "\007\000\002\050\002\000\002\022\005\000\002\022\003" +
    "\000\002\026\006\000\002\024\005\000\002\024\006\000" +
    "\002\025\004\000\002\025\003\000\002\023\005\000\002" +
    "\023\005\000\002\023\005\000\002\023\005\000\002\023" +
    "\005\000\002\023\005\000\002\023\005\000\002\023\005" +
    "\000\002\023\005\000\002\023\004\000\002\051\002\000" +
    "\002\023\006\000\002\023\003\000\002\023\006\000\002" +
    "\023\003\000\002\023\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\243\000\006\017\ufffe\047\ufffe\001\002\000\006\017" +
    "\011\047\012\001\002\000\004\002\006\001\002\000\004" +
    "\002\000\001\002\000\004\002\001\001\002\000\006\017" +
    "\uffff\047\uffff\001\002\000\004\020\ufff9\001\002\000\010" +
    "\024\014\025\016\053\013\001\002\000\004\010\233\001" +
    "\002\000\004\053\uffde\001\002\000\004\053\017\001\002" +
    "\000\004\053\uffdd\001\002\000\004\010\020\001\002\000" +
    "\010\011\ufffa\024\ufffa\025\ufffa\001\002\000\010\011\022" +
    "\024\014\025\016\001\002\000\004\050\032\001\002\000" +
    "\004\053\025\001\002\000\010\011\ufffb\024\ufffb\025\ufffb" +
    "\001\002\000\012\011\uffe0\012\027\024\uffe0\025\uffe0\001" +
    "\002\000\010\011\uffdf\024\uffdf\025\uffdf\001\002\000\004" +
    "\054\030\001\002\000\004\013\031\001\002\000\016\011" +
    "\uffc7\024\uffc7\025\uffc7\033\uffc7\036\uffc7\053\uffc7\001\002" +
    "\000\024\022\ufff5\023\ufff5\024\ufff5\025\ufff5\031\ufff5\037" +
    "\ufff5\045\ufff5\052\ufff5\053\ufff5\001\002\000\024\022\034" +
    "\023\045\024\014\025\016\031\050\037\041\045\055\052" +
    "\037\053\042\001\002\000\004\053\230\001\002\000\004" +
    "\053\212\001\002\000\040\021\ufff6\022\ufff6\023\ufff6\024" +
    "\ufff6\025\ufff6\031\ufff6\034\ufff6\035\ufff6\037\ufff6\044\ufff6" +
    "\045\ufff6\046\ufff6\051\ufff6\052\ufff6\053\ufff6\001\002\000" +
    "\014\010\062\030\057\053\056\054\060\055\061\001\002" +
    "\000\006\033\200\036\201\001\002\000\004\053\165\001" +
    "\002\000\010\010\136\012\027\036\135\001\002\000\040" +
    "\021\ufff4\022\ufff4\023\ufff4\024\ufff4\025\ufff4\031\ufff4\034" +
    "\ufff4\035\ufff4\037\ufff4\044\ufff4\045\ufff4\046\ufff4\051\ufff4" +
    "\052\ufff4\053\ufff4\001\002\000\040\021\uffee\022\uffee\023" +
    "\uffee\024\uffee\025\uffee\031\uffee\034\uffee\035\uffee\037\uffee" +
    "\044\uffee\045\uffee\046\uffee\051\uffee\052\uffee\053\uffee\001" +
    "\002\000\014\010\062\030\057\053\056\054\060\055\061" +
    "\001\002\000\040\021\ufff0\022\ufff0\023\ufff0\024\ufff0\025" +
    "\ufff0\031\ufff0\034\ufff0\035\ufff0\037\ufff0\044\ufff0\045\ufff0" +
    "\046\ufff0\051\ufff0\052\ufff0\053\ufff0\001\002\000\040\021" +
    "\ufff3\022\ufff3\023\ufff3\024\ufff3\025\ufff3\031\ufff3\034\ufff3" +
    "\035\ufff3\037\ufff3\044\ufff3\045\ufff3\046\ufff3\051\ufff3\052" +
    "\ufff3\053\ufff3\001\002\000\014\010\062\030\057\053\056" +
    "\054\060\055\061\001\002\000\040\021\uffed\022\uffed\023" +
    "\uffed\024\uffed\025\uffed\031\uffed\034\uffed\035\uffed\037\uffed" +
    "\044\uffed\045\uffed\046\uffed\051\uffed\052\uffed\053\uffed\001" +
    "\002\000\040\021\uffef\022\uffef\023\uffef\024\uffef\025\uffef" +
    "\031\uffef\034\uffef\035\uffef\037\uffef\044\uffef\045\uffef\046" +
    "\uffef\051\uffef\052\uffef\053\uffef\001\002\000\040\021\ufff1" +
    "\022\ufff1\023\ufff1\024\ufff1\025\ufff1\031\ufff1\034\ufff1\035" +
    "\ufff1\037\ufff1\044\ufff1\045\ufff1\046\ufff1\051\ufff1\052\ufff1" +
    "\053\ufff1\001\002\000\040\021\ufff2\022\ufff2\023\ufff2\024" +
    "\ufff2\025\ufff2\031\ufff2\034\ufff2\035\ufff2\037\ufff2\044\ufff2" +
    "\045\ufff2\046\ufff2\051\ufff2\052\ufff2\053\ufff2\001\002\000" +
    "\014\010\062\030\057\053\056\054\060\055\061\001\002" +
    "\000\050\004\uffb6\005\uffb6\006\uffb6\007\uffb6\010\uffb6\011" +
    "\uffb6\012\116\014\uffb6\015\uffb6\016\uffb6\026\uffb6\027\uffb6" +
    "\030\uffb6\032\uffb6\033\uffb6\043\uffb6\053\uffb6\054\uffb6\055" +
    "\uffb6\001\002\000\014\010\062\030\057\053\056\054\060" +
    "\055\061\001\002\000\046\004\uffb4\005\uffb4\006\uffb4\007" +
    "\uffb4\010\uffb4\011\uffb4\014\uffb4\015\uffb4\016\uffb4\026\uffb4" +
    "\027\uffb4\030\uffb4\032\uffb4\033\uffb4\043\uffb4\053\uffb4\054" +
    "\uffb4\055\uffb4\001\002\000\046\004\uffb3\005\uffb3\006\uffb3" +
    "\007\uffb3\010\uffb3\011\uffb3\014\uffb3\015\uffb3\016\uffb3\026" +
    "\uffb3\027\uffb3\030\uffb3\032\uffb3\033\uffb3\043\uffb3\053\uffb3" +
    "\054\uffb3\055\uffb3\001\002\000\014\010\062\030\057\053" +
    "\056\054\060\055\061\001\002\000\026\004\067\005\064" +
    "\006\072\007\065\014\074\015\066\016\070\026\075\027" +
    "\073\043\071\001\002\000\014\010\062\030\057\053\056" +
    "\054\060\055\061\001\002\000\014\010\062\030\057\053" +
    "\056\054\060\055\061\001\002\000\014\010\062\030\057" +
    "\053\056\054\060\055\061\001\002\000\014\010\062\030" +
    "\057\053\056\054\060\055\061\001\002\000\014\010\062" +
    "\030\057\053\056\054\060\055\061\001\002\000\024\022" +
    "\uffe2\023\uffe2\024\uffe2\025\uffe2\031\uffe2\037\uffe2\045\uffe2" +
    "\046\uffe2\053\uffe2\001\002\000\014\010\062\030\057\053" +
    "\056\054\060\055\061\001\002\000\014\010\062\030\057" +
    "\053\056\054\060\055\061\001\002\000\014\010\062\030" +
    "\057\053\056\054\060\055\061\001\002\000\014\010\062" +
    "\030\057\053\056\054\060\055\061\001\002\000\046\004" +
    "\uffbb\005\uffbb\006\uffbb\007\uffbb\010\uffbb\011\uffbb\014\uffbb" +
    "\015\uffbb\016\uffbb\026\uffbb\027\uffbb\030\uffbb\032\uffbb\033" +
    "\uffbb\043\uffbb\053\uffbb\054\uffbb\055\uffbb\001\002\000\046" +
    "\004\067\005\064\006\072\007\065\010\uffbe\011\uffbe\014" +
    "\uffbe\015\066\016\070\026\075\027\073\030\uffbe\032\uffbe" +
    "\033\uffbe\043\uffbe\053\uffbe\054\uffbe\055\uffbe\001\002\000" +
    "\046\004\uffba\005\uffba\006\uffba\007\uffba\010\uffba\011\uffba" +
    "\014\uffba\015\uffba\016\uffba\026\uffba\027\uffba\030\uffba\032" +
    "\uffba\033\uffba\043\uffba\053\uffba\054\uffba\055\uffba\001\002" +
    "\000\046\004\uffc0\005\uffc0\006\uffc0\007\uffc0\010\uffc0\011" +
    "\uffc0\014\uffc0\015\uffc0\016\uffc0\026\075\027\073\030\uffc0" +
    "\032\uffc0\033\uffc0\043\uffc0\053\uffc0\054\uffc0\055\uffc0\001" +
    "\002\000\024\022\ufff5\023\ufff5\024\ufff5\025\ufff5\031\ufff5" +
    "\037\ufff5\045\ufff5\046\ufff5\053\ufff5\001\002\000\024\022" +
    "\034\023\045\024\014\025\016\031\050\037\041\045\055" +
    "\046\104\053\042\001\002\000\040\021\uffe1\022\uffe1\023" +
    "\uffe1\024\uffe1\025\uffe1\031\uffe1\034\uffe1\035\uffe1\037\uffe1" +
    "\044\uffe1\045\uffe1\046\uffe1\051\uffe1\052\uffe1\053\uffe1\001" +
    "\002\000\046\004\067\005\064\006\072\007\065\010\uffbc" +
    "\011\uffbc\014\uffbc\015\uffbc\016\uffbc\026\075\027\073\030" +
    "\uffbc\032\uffbc\033\uffbc\043\uffbc\053\uffbc\054\uffbc\055\uffbc" +
    "\001\002\000\046\004\uffc2\005\uffc2\006\072\007\065\010" +
    "\uffc2\011\uffc2\014\uffc2\015\uffc2\016\uffc2\026\075\027\073" +
    "\030\uffc2\032\uffc2\033\uffc2\043\uffc2\053\uffc2\054\uffc2\055" +
    "\uffc2\001\002\000\046\004\067\005\064\006\072\007\065" +
    "\010\uffbd\011\uffbd\014\uffbd\015\uffbd\016\uffbd\026\075\027" +
    "\073\030\uffbd\032\uffbd\033\uffbd\043\uffbd\053\uffbd\054\uffbd" +
    "\055\uffbd\001\002\000\046\004\uffbf\005\uffbf\006\uffbf\007" +
    "\uffbf\010\uffbf\011\uffbf\014\uffbf\015\uffbf\016\uffbf\026\075" +
    "\027\073\030\uffbf\032\uffbf\033\uffbf\043\uffbf\053\uffbf\054" +
    "\uffbf\055\uffbf\001\002\000\046\004\uffc1\005\uffc1\006\072" +
    "\007\065\010\uffc1\011\uffc1\014\uffc1\015\uffc1\016\uffc1\026" +
    "\075\027\073\030\uffc1\032\uffc1\033\uffc1\043\uffc1\053\uffc1" +
    "\054\uffc1\055\uffc1\001\002\000\026\004\067\005\064\006" +
    "\072\007\065\011\uffb8\014\074\015\066\016\070\026\075" +
    "\027\073\001\002\000\004\011\114\001\002\000\046\004" +
    "\uffb7\005\uffb7\006\uffb7\007\uffb7\010\uffb7\011\uffb7\014\uffb7" +
    "\015\uffb7\016\uffb7\026\uffb7\027\uffb7\030\uffb7\032\uffb7\033" +
    "\uffb7\043\uffb7\053\uffb7\054\uffb7\055\uffb7\001\002\000\046" +
    "\004\uffb9\005\uffb9\006\uffb9\007\uffb9\010\uffb9\011\uffb9\014" +
    "\uffb9\015\uffb9\016\uffb9\026\uffb9\027\uffb9\030\uffb9\032\uffb9" +
    "\033\uffb9\043\uffb9\053\uffb9\054\uffb9\055\uffb9\001\002\000" +
    "\004\054\117\001\002\000\004\013\120\001\002\000\046" +
    "\004\uffb5\005\uffb5\006\uffb5\007\uffb5\010\uffb5\011\uffb5\014" +
    "\uffb5\015\uffb5\016\uffb5\026\uffb5\027\uffb5\030\uffb5\032\uffb5" +
    "\033\uffb5\043\uffb5\053\uffb5\054\uffb5\055\uffb5\001\002\000" +
    "\026\004\067\005\064\006\072\007\065\014\074\015\066" +
    "\016\070\026\075\027\073\033\uffe8\001\002\000\004\033" +
    "\123\001\002\000\024\022\uffe7\023\uffe7\024\uffe7\025\uffe7" +
    "\031\uffe7\034\uffe7\037\uffe7\045\uffe7\053\uffe7\001\002\000" +
    "\024\022\ufff5\023\ufff5\024\ufff5\025\ufff5\031\ufff5\034\ufff5" +
    "\037\ufff5\045\ufff5\053\ufff5\001\002\000\024\022\034\023" +
    "\045\024\014\025\016\031\050\034\126\037\041\045\055" +
    "\053\042\001\002\000\024\022\uffe6\023\uffe6\024\uffe6\025" +
    "\uffe6\031\uffe6\035\uffe6\037\uffe6\045\uffe6\053\uffe6\001\002" +
    "\000\024\022\ufff5\023\ufff5\024\ufff5\025\ufff5\031\ufff5\035" +
    "\ufff5\037\ufff5\045\ufff5\053\ufff5\001\002\000\024\022\034" +
    "\023\045\024\014\025\016\031\050\035\131\037\041\045" +
    "\055\053\042\001\002\000\040\021\uffe5\022\uffe5\023\uffe5" +
    "\024\uffe5\025\uffe5\031\uffe5\034\uffe5\035\uffe5\037\uffe5\044" +
    "\uffe5\045\uffe5\046\uffe5\051\uffe5\052\uffe5\053\uffe5\001\002" +
    "\000\026\004\067\005\064\006\072\007\065\014\074\015" +
    "\066\016\070\026\075\027\073\032\uffec\001\002\000\004" +
    "\032\134\001\002\000\040\021\uffeb\022\uffeb\023\uffeb\024" +
    "\uffeb\025\uffeb\031\uffeb\034\uffeb\035\uffeb\037\uffeb\044\uffeb" +
    "\045\uffeb\046\uffeb\051\uffeb\052\uffeb\053\uffeb\001\002\000" +
    "\014\010\062\030\057\053\160\054\060\055\061\001\002" +
    "\000\016\010\uffd0\011\uffcd\030\uffd0\053\137\054\uffd0\055" +
    "\uffd0\001\002\000\004\012\027\001\002\000\006\011\154" +
    "\053\uffca\001\002\000\006\011\uffc8\053\uffc8\001\002\000" +
    "\004\011\152\001\002\000\014\010\062\030\057\053\056" +
    "\054\060\055\061\001\002\000\016\010\062\011\146\030" +
    "\057\053\056\054\060\055\061\001\002\000\042\004\067" +
    "\005\064\006\072\007\065\010\uffc3\011\uffc3\014\074\015" +
    "\066\016\070\026\075\027\073\030\uffc3\032\uffc3\053\uffc3" +
    "\054\uffc3\055\uffc3\001\002\000\004\032\uffcf\001\002\000" +
    "\042\004\067\005\064\006\072\007\065\010\uffc4\011\uffc4" +
    "\014\074\015\066\016\070\026\075\027\073\030\uffc4\032" +
    "\uffc4\053\uffc4\054\uffc4\055\uffc4\001\002\000\004\032\151" +
    "\001\002\000\040\021\uffce\022\uffce\023\uffce\024\uffce\025" +
    "\uffce\031\uffce\034\uffce\035\uffce\037\uffce\044\uffce\045\uffce" +
    "\046\uffce\051\uffce\052\uffce\053\uffce\001\002\000\004\032" +
    "\153\001\002\000\040\021\uffcc\022\uffcc\023\uffcc\024\uffcc" +
    "\025\uffcc\031\uffcc\034\uffcc\035\uffcc\037\uffcc\044\uffcc\045" +
    "\uffcc\046\uffcc\051\uffcc\052\uffcc\053\uffcc\001\002\000\004" +
    "\032\157\001\002\000\004\053\137\001\002\000\006\011" +
    "\uffc9\053\uffc9\001\002\000\040\021\uffcb\022\uffcb\023\uffcb" +
    "\024\uffcb\025\uffcb\031\uffcb\034\uffcb\035\uffcb\037\uffcb\044" +
    "\uffcb\045\uffcb\046\uffcb\051\uffcb\052\uffcb\053\uffcb\001\002" +
    "\000\032\004\uffb6\005\uffb6\006\uffb6\007\uffb6\010\136\012" +
    "\116\014\uffb6\015\uffb6\016\uffb6\026\uffb6\027\uffb6\032\uffb6" +
    "\001\002\000\026\004\067\005\064\006\072\007\065\014" +
    "\074\015\066\016\070\026\075\027\073\032\uffd5\001\002" +
    "\000\040\021\uffd3\022\uffd3\023\uffd3\024\uffd3\025\uffd3\031" +
    "\uffd3\034\uffd3\035\uffd3\037\uffd3\044\uffd3\045\uffd3\046\uffd3" +
    "\051\uffd3\052\uffd3\053\uffd3\001\002\000\004\032\164\001" +
    "\002\000\040\021\uffd4\022\uffd4\023\uffd4\024\uffd4\025\uffd4" +
    "\031\uffd4\034\uffd4\035\uffd4\037\uffd4\044\uffd4\045\uffd4\046" +
    "\uffd4\051\uffd4\052\uffd4\053\uffd4\001\002\000\004\040\166" +
    "\001\002\000\004\054\167\001\002\000\004\041\170\001" +
    "\002\000\004\054\171\001\002\000\004\042\172\001\002" +
    "\000\004\054\173\001\002\000\004\043\174\001\002\000" +
    "\024\022\uffe4\023\uffe4\024\uffe4\025\uffe4\031\uffe4\037\uffe4" +
    "\044\uffe4\045\uffe4\053\uffe4\001\002\000\024\022\ufff5\023" +
    "\ufff5\024\ufff5\025\ufff5\031\ufff5\037\ufff5\044\ufff5\045\ufff5" +
    "\053\ufff5\001\002\000\024\022\034\023\045\024\014\025" +
    "\016\031\050\037\041\044\177\045\055\053\042\001\002" +
    "\000\040\021\uffe3\022\uffe3\023\uffe3\024\uffe3\025\uffe3\031" +
    "\uffe3\034\uffe3\035\uffe3\037\uffe3\044\uffe3\045\uffe3\046\uffe3" +
    "\051\uffe3\052\uffe3\053\uffe3\001\002\000\004\036\204\001" +
    "\002\000\014\010\062\030\057\053\056\054\060\055\061" +
    "\001\002\000\026\004\067\005\064\006\072\007\065\014" +
    "\074\015\066\016\070\026\075\027\073\032\203\001\002" +
    "\000\040\021\uffd2\022\uffd2\023\uffd2\024\uffd2\025\uffd2\031" +
    "\uffd2\034\uffd2\035\uffd2\037\uffd2\044\uffd2\045\uffd2\046\uffd2" +
    "\051\uffd2\052\uffd2\053\uffd2\001\002\000\004\053\205\001" +
    "\002\000\004\010\136\001\002\000\040\021\uffd1\022\uffd1" +
    "\023\uffd1\024\uffd1\025\uffd1\031\uffd1\034\uffd1\035\uffd1\037" +
    "\uffd1\044\uffd1\045\uffd1\046\uffd1\051\uffd1\052\uffd1\053\uffd1" +
    "\001\002\000\016\010\062\030\057\032\210\053\056\054" +
    "\060\055\061\001\002\000\004\051\211\001\002\000\006" +
    "\017\ufffd\047\ufffd\001\002\000\010\012\215\032\uffda\036" +
    "\214\001\002\000\004\032\227\001\002\000\014\010\062" +
    "\030\057\053\056\054\060\055\061\001\002\000\004\054" +
    "\221\001\002\000\004\036\217\001\002\000\004\053\205" +
    "\001\002\000\040\021\uffd7\022\uffd7\023\uffd7\024\uffd7\025" +
    "\uffd7\031\uffd7\034\uffd7\035\uffd7\037\uffd7\044\uffd7\045\uffd7" +
    "\046\uffd7\051\uffd7\052\uffd7\053\uffd7\001\002\000\004\013" +
    "\222\001\002\000\004\032\223\001\002\000\040\021\uffd6" +
    "\022\uffd6\023\uffd6\024\uffd6\025\uffd6\031\uffd6\034\uffd6\035" +
    "\uffd6\037\uffd6\044\uffd6\045\uffd6\046\uffd6\051\uffd6\052\uffd6" +
    "\053\uffd6\001\002\000\026\004\067\005\064\006\072\007" +
    "\065\014\074\015\066\016\070\026\075\027\073\032\uffdc" +
    "\001\002\000\004\032\226\001\002\000\040\021\uffdb\022" +
    "\uffdb\023\uffdb\024\uffdb\025\uffdb\031\uffdb\034\uffdb\035\uffdb" +
    "\037\uffdb\044\uffdb\045\uffdb\046\uffdb\051\uffdb\052\uffdb\053" +
    "\uffdb\001\002\000\040\021\uffd9\022\uffd9\023\uffd9\024\uffd9" +
    "\025\uffd9\031\uffd9\034\uffd9\035\uffd9\037\uffd9\044\uffd9\045" +
    "\uffd9\046\uffd9\051\uffd9\052\uffd9\053\uffd9\001\002\000\004" +
    "\032\uffea\001\002\000\004\032\232\001\002\000\040\021" +
    "\uffe9\022\uffe9\023\uffe9\024\uffe9\025\uffe9\031\uffe9\034\uffe9" +
    "\035\uffe9\037\uffe9\044\uffe9\045\uffe9\046\uffe9\051\uffe9\052" +
    "\uffe9\053\uffe9\001\002\000\010\011\ufffa\024\ufffa\025\ufffa" +
    "\001\002\000\010\011\235\024\014\025\016\001\002\000" +
    "\004\050\236\001\002\000\024\022\ufff5\023\ufff5\024\ufff5" +
    "\025\ufff5\031\ufff5\037\ufff5\045\ufff5\051\ufff5\053\ufff5\001" +
    "\002\000\024\022\034\023\045\024\014\025\016\031\050" +
    "\037\041\045\055\051\240\053\042\001\002\000\006\017" +
    "\ufffc\047\ufffc\001\002\000\004\020\242\001\002\000\024" +
    "\021\ufff8\022\ufff8\023\ufff8\024\ufff8\025\ufff8\031\ufff8\037" +
    "\ufff8\045\ufff8\053\ufff8\001\002\000\024\021\ufff5\022\ufff5" +
    "\023\ufff5\024\ufff5\025\ufff5\031\ufff5\037\ufff5\045\ufff5\053" +
    "\ufff5\001\002\000\024\021\245\022\034\023\045\024\014" +
    "\025\016\031\050\037\041\045\055\053\042\001\002\000" +
    "\004\002\ufff7\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\243\000\006\002\004\017\003\001\001\000\006\003" +
    "\006\020\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\030\240\001" +
    "\001\000\004\027\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\015\020\001\001\000\006\016\023\027\022" +
    "\001\001\000\002\001\001\000\004\026\025\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\032\001\001\000\030\005\035\006\046\007\053\010\052" +
    "\011\042\012\045\013\051\014\043\021\050\026\037\027" +
    "\034\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\023\144\025\206\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\023\131\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\023\120\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\023\062\001\001\000\002\001\001\000\004" +
    "\023\114\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\023\111\001\001\000\002\001\001\000\004\023\110" +
    "\001\001\000\004\023\107\001\001\000\004\023\106\001" +
    "\001\000\004\023\105\001\001\000\004\023\104\001\001" +
    "\000\004\040\101\001\001\000\004\023\100\001\001\000" +
    "\004\023\077\001\001\000\004\023\076\001\001\000\004" +
    "\023\075\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\004\102\001\001" +
    "\000\030\005\035\006\046\007\053\010\052\011\042\012" +
    "\045\013\051\014\043\021\050\026\037\027\034\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\051\112\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\034\121\001\001\000\002\001\001\000" +
    "\004\035\123\001\001\000\004\004\124\001\001\000\030" +
    "\005\035\006\046\007\053\010\052\011\042\012\045\013" +
    "\051\014\043\021\050\026\037\027\034\001\001\000\004" +
    "\036\126\001\001\000\004\004\127\001\001\000\030\005" +
    "\035\006\046\007\053\010\052\011\042\012\045\013\051" +
    "\014\043\021\050\026\037\027\034\001\001\000\002\001" +
    "\001\000\004\032\132\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\021\161\023\160\001\001\000\012\022" +
    "\137\026\140\045\142\047\141\001\001\000\002\001\001" +
    "\000\004\050\154\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\023\144\025\143\001\001\000\004\023\146" +
    "\001\001\000\002\001\001\000\004\046\147\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\026" +
    "\155\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\044\162\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\037\174" +
    "\001\001\000\004\004\175\001\001\000\030\005\035\006" +
    "\046\007\053\010\052\011\042\012\045\013\051\014\043" +
    "\021\050\026\037\027\034\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\023\201\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\021\205\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\023\146\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\042\212\043\215\001" +
    "\001\000\002\001\001\000\004\023\223\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\021\217\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\041\224\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\033\230\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\015\233\001" +
    "\001\000\006\016\023\027\022\001\001\000\002\001\001" +
    "\000\004\004\236\001\001\000\030\005\035\006\046\007" +
    "\053\010\052\011\042\012\045\013\051\014\043\021\050" +
    "\026\037\027\034\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\031\242\001\001\000\004\004\243\001\001" +
    "\000\030\005\035\006\046\007\053\010\052\011\042\012" +
    "\045\013\051\014\043\021\050\026\037\027\034\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




  //classe para permitir salvar tipo do token e o valor.
  class table_symbol {

       private String tipo;
       private String valor;

       table_symbol(String tipo, String valor){
          this.tipo = tipo;
          this.valor = valor;
       }

         table_symbol(String tipo){
          this.tipo = tipo;
       }

       public String getTipo(){
          return tipo;
       }

       public String getValor(){
          return valor;
       }

       public void setValor(String valor){
          this.valor = valor;
       }

  }

/** table of declared symbols -- contains production parts indexed by name */
   private Hashtable<String, table_symbol> symT = new Hashtable<String, table_symbol>();
   private static final String LEFT_PAR = "(";
   private static final String RIGHT_PAR = ")";
   private int POS = 0;
      
    /* Change the method report_error so it will display the line and
       column of where the error occurred in the input as well as the
       reason for the error which is passed into the method in the
       String 'message'. */
    public void report_error(String message, Object info) {
   
        /* Create a StringBuilder called 'm' with the string 'Error' in it. */
        StringBuilder m = new StringBuilder("Error");
   
        /* Check if the information passed to the method is the same
           type as the type java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the
               information in the object info that is being typecasted
               as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            /* Check if the line number in the input is greater or
               equal to zero. */
            if (s.left >= 0) {                
                /* Add to the end of the StringBuilder error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuilder error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }
   
        /* Add to the end of the StringBuilder error message created in
           this method the message that was passed into this method. */
        m.append(" : "+message);
   
        /* Print the contents of the StringBuilder 'm', which contains
           an error message, out on a line. */
        System.err.println(m);
    }
   
    /* Change the method report_fatal_error so when it reports a fatal
       error it will display the line and column number of where the
       fatal error occurred in the input as well as the reason for the
       fatal error which is passed into the method in the object
       'message' and then exit.*/
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

    public void format_code(){
       for(int i=0; i < POS * 3; i++){
          System.out.print(" ");
       }
    }

    
    public void update_symT(String id, String valor){

       table_symbol t = symT.get(id);
       t.setValor(valor);
       symT.replace(id,t);

    }

    public String check_expr(String e1, String e2){

      String res;
      
      if(! symT.containsKey(e1)) {
           report_fatal_error("Variavel nao declarada: " + e1, null);
      }   

      if(e2 == null){
         table_symbol te1 = symT.get(e1);
         String tp1 = te1.getTipo();
         res = tp1;
      } else {
         if(! symT.containsKey(e2)) {
           report_fatal_error("Variavel nao declarada: " + e1, null);
         }
         table_symbol te1 = symT.get(e1);
         table_symbol te2 = symT.get(e2);

         String tp1 = te1.getTipo();
         String tp2 = te2.getTipo();

         if(tp1.equals(tp2)){
           res = tp1;
         } else {
           res =  "FLOAT";
         }
      }
      return res;
    }



    /**************** emit code *****************/

    public void emit_program(){

       System.out.print("#include<stdio.h>\n");
       System.out.print("#include<stdlib.h>\n");
       System.out.print("\nint main()");

    }

    public void emit_startprogram(){

       System.out.print("{\n");

    }

 
     public void emit_endprg(){

       System.out.print("}\n");

    }

     public void emit_return(){

       System.out.print("return 0;\n");

    }

    public void emit_semi(){
        System.out.print(";\n");
    }

    public void emit_declare_variable_with_value(String id, String value, String tipo){

       if(symT.containsKey(id)){
          report_fatal_error("Variável duplicada [" + id + "]",null);
       }
       symT.put(id,new table_symbol(tipo,value));
       System.out.print(id + "=" + value); 
              
    }

    public void emit_declare_variable_without_value(String id, String tipo){

      if(symT.containsKey(id)){
          report_fatal_error("Variável duplicada [" + id + "]",null);
       } 

       symT.put(id,new table_symbol(tipo));
       System.out.print(id); 
    }

    public void emit_assign_id_expr(String id, String value){
      
       if(! symT.containsKey(id)) {
           report_fatal_error("Variavel nao declarada: " + id, null);
      } else {    

            System.out.print(id + "=" + value); 
            update_symT(id,value);
      }
  

    }
    
    public void emit_if(String e){

       System.out.print("if(" + e + ")");
    }


    public void emit_escreva(String id){

      if(! symT.containsKey(id)) {
           report_fatal_error("Variavel nao declarada: " + id, null);
      } else {    

         String tipo = (symT.get(id)).getTipo();

         if(tipo.equals("INT")) {
            System.out.print("printf(\"\\n%d\"," + id + ")") ;
         } else {
            System.out.print("printf(\"\\n%f\"," + id + ")");
         }   
      }
    }

        public void emit_leia(String id){

      if(! symT.containsKey(id)) {
           report_fatal_error("Variavel nao declarada: " + id, null);
      } else {    
         String tipo = (symT.get(id)).getTipo();

         if(tipo.equals("INT")) {
            System.out.print("scanf(\"%d\",&" + id + ")");
         } else {
            System.out.print("scanf(\"%f\",&" + id + ")");
         }   
      }
    }

    public void emit_for(String id, String i1, String i2, String i3){
       System.out.print("for(" + id + "=" + i1 + ";" + id + "<" + i2 + ";" + id + "+=" + i3 + "){\n" );
    }

    public void emit_else(){
       System.out.print("else{\n");
    }

    public void emit_while(String e){
      System.out.print("while(" + e + "){\n");     
    }

    public void emit_vector(String id, String num){

      System.out.print(id + "[" + num + "];\n");

    }

    public void emit_func(String id){
       System.out.print(id + "(");
    }

    public void emit_inteiro(){
       System.out.print("int ");
    }

    public void emit_flutuante(){
       System.out.print("float ");
    }

    public void emit_declare_vector(String t, String id, String i){

      if(symT.containsKey(id)){
          report_fatal_error("Variável duplicada [" + id + "]",null);
       } 

       symT.put(id,new table_symbol(t));
       System.out.print(id + "["+i+"]");

    }

    public String check_id( String id, String i){

      if(! symT.containsKey(id)){
          report_fatal_error("Variável Não declarada [" + id + "]",null);
      } 

      symT.put(id+"["+i+"]",new table_symbol("TANTOFAZ"));
      
      return id+"["+i+"]";

    }

    public void emit_assign_vector(String v, String e){
       System.out.print(v+"="+e+";\n");
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // s ::= listafuncao program 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= s EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // listafuncao ::= listafuncao func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listafuncao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listafuncao ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listafuncao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // func ::= FUNCAO tipo ID LPAREN list_param RPAREN STARTFUNC list_command RETORNO expr_list SEMI ENDFUNC 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // func ::= FUNCAO ID LPAREN list_param RPAREN STARTFUNC list_command ENDFUNC 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // list_param ::= list_param param 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // list_param ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // NT$0 ::= 
            {
              Object RESULT =null;
 emit_program();               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$1 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 emit_startprogram() ; POS++;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // program ::= PROGRAM NT$0 STARTPRG NT$1 list_command ENDPRG 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 format_code(); emit_return(); POS--; format_code(); emit_endprg() ;        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // list_command ::= list_command command 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_command",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // list_command ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_command",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // command ::= declare_variable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // command ::= assign 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // command ::= writel 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // command ::= readl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // command ::= iff 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // command ::= for 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // command ::= while 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // command ::= chamafunc 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // NT$2 ::= 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_escreva(value);  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // writel ::= WRITELINE expr NT$2 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi();          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("writel",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NT$3 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_leia(id);   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // readl ::= READLINE ID NT$3 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi();     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("readl",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NT$4 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_if(e);  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // NT$5 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
 emit_startprogram(); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$5",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // NT$6 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
 POS--; format_code(); emit_endprg(); format_code(); emit_else(); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$6",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // iff ::= IFF expr NT$4 THENN NT$5 list_command ELSEE NT$6 list_command ENDELSE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		POS--; format_code(); System.out.print("}\n"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("iff",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT$7 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int i1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String i1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String i2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int i3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int i3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i3 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 format_code(); emit_for(id,i1,i2,i3); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$7",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // for ::= PARA ID DE INTT ATE INTT PASSO INTT FACA NT$7 list_command FIMPARA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-10)).value;
		int i1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		String i1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String i2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int i3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int i3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String i3 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 POS--; format_code(); emit_endprg(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("for",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // NT$8 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 format_code(); emit_while(e); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$8",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // while ::= ENQUANTO expr FACA NT$8 list_command FIMENQUANTO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$8
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 POS--; format_code(); emit_endprg(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // param ::= tipo ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // param ::= tipo vetor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // tipo ::= DECLINT 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = "INT"  ; format_code();  emit_inteiro();   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // tipo ::= DECLFLOAT 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = "FLOAT"; format_code();  emit_flutuante(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // NT$9 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_declare_variable_with_value(id,value,t);  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$9",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // declare_variable ::= tipo ID ATTRIB expr NT$9 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$9
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // NT$10 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_declare_variable_without_value(id,t); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$10",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // declare_variable ::= tipo ID NT$10 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$10
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi();  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // NT$11 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_declare_variable_without_value(id,t); System.out.print("="); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$11",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // declare_variable ::= tipo ID NT$11 ATTRIB chamafunc 
            {
              Object RESULT =null;
              // propagate RESULT from NT$11
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // declare_variable ::= tipo ID LBRCKT INTT RBRCKT SEMI 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_declare_vector(t,id,i); emit_semi(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // NT$12 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_assign_id_expr(id,value); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$12",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // assign ::= ID ATTRIB expr NT$12 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$12
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // assign ::= ID ATTRIB chamafunc 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // assign ::= vetor ATTRIB expr SEMI 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 format_code(); emit_assign_vector(v,e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // assign ::= vetor THENN ATTRIB chamafunc 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // NT$13 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 emit_func(id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$13",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // NT$14 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
 System.out.print(");\n"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$14",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // chamafunc ::= ID LPAREN NT$13 expr_list RPAREN NT$14 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$14
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("chamafunc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // NT$15 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 emit_func(id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$15",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // chamafunc ::= ID LPAREN NT$15 RPAREN SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$15
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("chamafunc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // chamafunc ::= ID LPAREN vetor_list RPAREN SEMI 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("chamafunc",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // NT$16 ::= 
            {
              Object RESULT =null;
 System.out.print(", "); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$16",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // vetor_list ::= vetor_list NT$16 vetor 
            {
              Object RESULT =null;
              // propagate RESULT from NT$16
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("vetor_list",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // vetor_list ::= vetor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("vetor_list",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // vetor ::= ID LBRCKT INTT RBRCKT 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = id+"["+i+"]"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vetor",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr_vetor ::= expr_vetor PLUS expr_vetor 
            {
              String RESULT =null;
		int ev1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int ev1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String ev1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ev2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ev2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String ev2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  ev1 + "+" + ev2;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_vetor",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr_vetor ::= ID LBRCKT INTT RBRCKT 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = id ; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_vetor",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr_list ::= expr_list expr 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr_list ::= expr 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= expr PLUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "+" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= expr MINUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "-" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= expr TIMES expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "*" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= expr DIVIDE expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "/" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr ::= expr EQUALS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "==" + e2; symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expr ::= expr GREATER expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + ">" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expr ::= expr LESS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "<" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expr ::= expr E expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "&&" + e2; symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expr ::= expr OU expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "||" + e2; symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expr ::= NAO expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =   "!" + e1;  symT.put(RESULT,new table_symbol(check_expr(e1,null),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // NT$17 ::= 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 RESULT =  "(" + e1  + ")";symT.put(RESULT,new table_symbol(check_expr(e1,null),RESULT)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$17",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expr ::= LPAREN expr NT$17 RPAREN 
            {
              String RESULT =null;
              // propagate RESULT from NT$17
                RESULT = (String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expr ::= ID 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = i;                                                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // expr ::= ID LBRCKT INTT RBRCKT 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		  RESULT = check_id(id,i);                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // expr ::= INTT 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n;  symT.put(n,new table_symbol("INT",n));                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // expr ::= FLOATT 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n;  symT.put(n,new table_symbol("FLOAT",n));                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
